### PR TITLE
add alt to image #51

### LINKED ISSUE #51: Add alts to images
All of the images in the markdown files don't have alts, and there's a lot to get through.

You can find all the files in the `notes` directory

Comment on the issue if you need any help

### PR DESCRIPTION
**Pull request by djgovani**
fixed #51

### CODE REVIEW

**Review by samrobbins85 — APPROVED** [review]
Looks great thanks

**Comment by samrobbins85** [comment]
To anyone else looking at this, it doesn't fully fix #51, there are lots of images in the markdown to add alts to, but this is a great improvement!

**Comment by djgovani** [comment]
> To anyone else looking at this, it doesn't fully fix #51, there are lots of images in the markdown to add alts to, but this is a great improvement!

Thanks @samrobbins85 for merging PR. I have searched the `` tag and found only this add alt change in the project.

**Comment by samrobbins85** [comment]
Hi, the images are included in all the markdown files, and so aren't directly represented as img tags

**Pull request merged**
